### ISSUE TITLE
Problem with PetSafe Android app for WiFi Enterprise

### ISSUE THREAD

**Issue by DarkCTO** [Drjacky/Drjacky#1]
Hello,
I am currently working on a senior design project that involves PetSafe feeder.
The app only provides password field after choosing from list of networks from app.
Now, with WiFi enterprise in my school, there is supposed to be a name field as well.
Seems like the android app does not support WiFi Enterprise WPA2 correct?

**Comment by Drjacky** [comment]
Please get in touch with the customer service through their own channels.
